twig:
    default_path: '%kernel.project_dir%/templates'
    #Conjunto de estilos que serão usados para renderizar formulários
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
